In [3]:
import pyreadstat
import pandas as pd

# Path to your .XPT file (update this with your actual file location)
input_path = "/Users/deirdreoconnor/Downloads/LLCP2022.XPT"
output_path = "/Users/deirdreoconnor/Downloads/LLCP2022.csv"

print("📥 Reading the .XPT file... (this may take a few minutes)")
df, meta = pyreadstat.read_xport(input_path)

print("✅ File loaded successfully!")
print("Shape of dataset:", df.shape)

print("💾 Converting to CSV...")
df.to_csv(output_path, index=False)
print(f"✅ Conversion complete! CSV saved to: {output_path}")

📥 Reading the .XPT file... (this may take a few minutes)

PyreadstatError: File /Users/deirdreoconnor/Downloads/LLCP2022.XPT does not exist!

In [5]:
pip install pandas pyreadstat

import pyreadstat
import pandas as pd
import os

# Update this path to where your .XPT file is actually located
input_path = "/Users/deirdreoconnor/Downloads/LLCP2022.XPT"
output_path = "/Users/deirdreoconnor/Downloads/LLCP2022.csv"

# Check if the file exists before attempting to read it
if os.path.exists(input_path):
    print("📥 Reading the .XPT file... (this may take a few minutes)")
    df, meta = pyreadstat.read_xport(input_path)
    
    print("✅ File loaded successfully!")
    print("Shape of dataset:", df.shape)
    
    print("💾 Converting to CSV...")
    df.to_csv(output_path, index=False)
    print(f"✅ Conversion complete! CSV saved to: {output_path}")
else:
    print(f"❌ Error: The file {input_path} does not exist.")
    print("Please check that:")
    print("1. The file name is correct")
    print("2. The file is in the specified directory")
    print("3. You have the necessary permissions to access the file")

❌ Error: The file /Users/deirdreoconnor/Downloads/LLCP2022.XPT does not exist.
Please check that:
1. The file name is correct
2. The file is in the specified directory
3. You have the necessary permissions to access the file

In [8]:
import pyreadstat
import pandas as pd
import os
import glob

# Path to your .XPT file
input_path = "LLCP2022.XPT "
output_path = "LLCP2022.csv"

# Troubleshooting section
print("🔍 Troubleshooting file access...")
print(f"Checking if file exists at: {input_path}")
file_exists = os.path.exists(input_path)
print(f"File exists check result: {file_exists}")

if not file_exists:
    # Look for similar files in the directory
    directory = os.path.dirname(input_path)
    print(f"Looking for .XPT files in: {directory}")
    xpt_files = glob.glob(os.path.join(directory, "*.XPT"))
    xpt_files_case_insensitive = glob.glob(os.path.join(directory, "*.xpt"))
    
    all_xpt_files = xpt_files + xpt_files_case_insensitive
    if all_xpt_files:
        print("Found these .XPT files:")
        for file in all_xpt_files:
            print(f"  - {os.path.basename(file)}")
        print("You might want to use one of these instead.")
    else:
        print("No .XPT files found in the directory.")
    
    # Check permissions
    try:
        if os.path.exists(directory):
            print(f"Directory exists. Checking if it's readable...")
            os.listdir(directory)
            print("Directory is readable.")
        else:
            print(f"Directory {directory} does not exist!")
    except PermissionError:
        print(f"Permission denied when trying to access {directory}")

# Try to read the file with explicit error handling
try:
    print("\n📥 Attempting to read the .XPT file...")
    df, meta = pyreadstat.read_xport(input_path)
    
    print("✅ File loaded successfully!")
    print("Shape of dataset:", df.shape)
    
    print("💾 Converting to CSV...")
    df.to_csv(output_path, index=False)
    print(f"✅ Conversion complete! CSV saved to: {output_path}")
except Exception as e:
    print(f"❌ Error: {str(e)}")
    print("\nPossible solutions:")
    print("1. Check if the file name has correct capitalization (LLCP2022.XPT vs llcp2022.xpt)")
    print("2. Try using the absolute path with raw string: r'/Users/deirdreoconnor/Downloads/LLCP2022.XPT'")
    print("3. Make sure the file isn't corrupted or incomplete")
    print("4. Check if you have the latest version of pyreadstat")
    print("5. Try opening the file with a different library like pandas directly:")
    print("   import pandas as pd")
    print("   df = pd.read_sas('/Users/deirdreoconnor/Downloads/LLCP2022.XPT', format='xport')")

🔍 Troubleshooting file access...
Checking if file exists at: LLCP2022.XPT
File exists check result: True

📥 Attempting to read the .XPT file...
❌ Error: 'utf-8' codec can't decode byte 0xb4 in position 5: invalid start byte

Possible solutions:
1. Check if the file name has correct capitalization (LLCP2022.XPT vs llcp2022.xpt)
2. Try using the absolute path with raw string: r'/Users/deirdreoconnor/Downloads/LLCP2022.XPT'
3. Make sure the file isn't corrupted or incomplete
4. Check if you have the latest version of pyreadstat
5. Try opening the file with a different library like pandas directly:
   import pandas as pd
   df = pd.read_sas('/Users/deirdreoconnor/Downloads/LLCP2022.XPT', format='xport')

In [11]:
import pandas as pd
df = pd.read_sas('LLCP2022.XPT', format='xport')

FileNotFoundError: [Errno 2] No such file or directory: 'LLCP2022.XPT'

In [10]:
import pandas as pd
df = pd.read_sas('LLCP2022.XPT', format='xport')

FileNotFoundError: [Errno 2] No such file or directory: 'LLCP2022.XPT'

In [ ]:
import pandas as pd

# Read the XPT file
df = pd.read_sas('/Users/deirdreoconnor/Desktop/Ai Start Course 2/Course Materials/Week 5/Week 5 - Additional Files/Demos/Code/LLCP2022.XPT ')

# Save as CSV
df.to_csv('output.csv', index=False)

print(f"Converted! Shape: {df.shape}")
df.head()  # Preview the first few rows

In [ ]:
import os
print(os.getcwd())  # Shows your current directory
print("\nFiles in current directory:")
for file in os.listdir():
    print(file)

In [ ]:
pythonimport pandas as pd

print("Reading XPT file...")
df = pd.read_sas('LLCP2022.XPT')

print(f"✓ File loaded! Shape: {df.shape}")
print(f"  Rows: {df.shape[0]:,}")
print(f"  Columns: {df.shape[1]}")

print("\nSaving to CSV...")
df.to_csv('output.csv', index=False)
print("✓ Done! File saved as output.csv")

In [ ]:
df.head()  # Preview the first few rows

In [1]:
import pandas as pd

# Update with your real CSV path
df = pd.read_csv("/Users/deirdreoconnor/Desktop/Ai Start Course 2/Course Materials/Week 5/Week 5 - Additional Files/Demos/Code/output.csv")

# Show how many columns and what they are
print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist()[:50])  # show the first 50 columns

Shape: (188473, 328)
Columns:
['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEQNO', '_PSU', 'CTELENM1', 'PVTRESD1', 'COLGHOUS', 'STATERE1', 'CELPHON1', 'LADULT1', 'COLGSEX1', 'NUMADULT', 'LANDSEX1', 'NUMMEN', 'NUMWOMEN', 'RESPSLCT', 'SAFETIME', 'CTELNUM1', 'CELLFON5', 'CADULT1', 'CELLSEX1', 'PVTRESD3', 'CCLGHOUS', 'CSTATE1', 'LANDLINE', 'HHADULT', 'SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINSR', 'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2', 'SLEPTIM1', 'LASTDEN4', 'RMVTETH4', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNC1']

In [2]:
# Choose only relevant columns
columns_to_keep = [
    "CVDCRHD4", "SEXVAR", "AGE80", "INCOME2", "EDUCA", "RACEGR3",
    "EMPLOY1", "MARITAL", "SMOKE100", "ALCDAY5", "EXERANY2",
    "SLEPTIM1", "FRUIT1", "VEGETAB1", "BMI5", "DIABETE4", "BPHIGH4",
    "CHOLCHK3", "GENHLTH", "MENTHLTH", "PHYSHLTH"
]

df_filtered = df[columns_to_keep]

# Save the filtered version
df_filtered.to_csv("/Users/deirdreoconnor/Desktop/Ai Start Course 2/Course Materials/Week 5/Week 5 - Additional Files/Demos/Code/HeartDiseaseSubset2022.csv", index=False)
print("✅ Filtered dataset saved successfully!")
print("Shape:", df_filtered.shape)

KeyError: "['AGE80', 'INCOME2', 'RACEGR3', 'ALCDAY5', 'FRUIT1', 'VEGETAB1', 'BMI5', 'BPHIGH4', 'CHOLCHK3'] not in index"

In [3]:
# First, let's see ALL column names to find the ones we need
print("All columns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

All columns:
1. _STATE
2. FMONTH
3. IDATE
4. IMONTH
5. IDAY
6. IYEAR
7. DISPCODE
8. SEQNO
9. _PSU
10. CTELENM1
11. PVTRESD1
12. COLGHOUS
13. STATERE1
14. CELPHON1
15. LADULT1
16. COLGSEX1
17. NUMADULT
18. LANDSEX1
19. NUMMEN
20. NUMWOMEN
21. RESPSLCT
22. SAFETIME
23. CTELNUM1
24. CELLFON5
25. CADULT1
26. CELLSEX1
27. PVTRESD3
28. CCLGHOUS
29. CSTATE1
30. LANDLINE
31. HHADULT
32. SEXVAR
33. GENHLTH
34. PHYSHLTH
35. MENTHLTH
36. POORHLTH
37. PRIMINSR
38. PERSDOC3
39. MEDCOST1
40. CHECKUP1
41. EXERANY2
42. SLEPTIM1
43. LASTDEN4
44. RMVTETH4
45. CVDINFR4
46. CVDCRHD4
47. CVDSTRK3
48. ASTHMA3
49. ASTHNOW
50. CHCSCNC1
51. CHCOCNC1
52. CHCCOPD3
53. ADDEPEV3
54. CHCKDNY2
55. HAVARTH4
56. DIABETE4
57. DIABAGE4
58. MARITAL
59. EDUCA
60. RENTHOM1
61. NUMHHOL4
62. NUMPHON4
63. CPDEMO1C
64. VETERAN3
65. EMPLOY1
66. CHILDREN
67. INCOME3
68. PREGNANT
69. WEIGHT2
70. HEIGHT3
71. DEAF
72. BLIND
73. DECIDE
74. DIFFWALK
75. DIFFDRES
76. DIFFALON
77. HADMAM
78. HOWLONG
79. CERVSCRN
80. CRVCLCNC
81. CRVCLPAP
82. CRVCLHPV
83. HADHYST2
84. HADSIGM4
85. COLNSIGM
86. COLNTES1
87. SIGMTES1
88. LASTSIG4
89. COLNCNCR
90. VIRCOLO1
91. VCLNTES2
92. SMALSTOL
93. STOLTEST
94. STOOLDN2
95. BLDSTFIT
96. SDNATES1
97. SMOKE100
98. SMOKDAY2
99. USENOW3
100. ECIGNOW2
101. LCSFIRST
102. LCSLAST
103. LCSNUMCG
104. LCSCTSC1
105. LCSSCNCR
106. LCSCTWHN
107. ALCDAY4
108. AVEDRNK3
109. DRNK3GE5
110. MAXDRNKS
111. FLUSHOT7
112. FLSHTMY3
113. PNEUVAC4
114. TETANUS1
115. HIVTST7
116. HIVTSTD3
117. HIVRISK5
118. COVIDPOS
119. COVIDSMP
120. COVIDPRM
121. PDIABTS1
122. PREDIAB2
123. DIABTYPE
124. INSULIN1
125. CHKHEMO3
126. EYEEXAM1
127. DIABEYE1
128. DIABEDU1
129. FEETSORE
130. TOLDCFS
131. HAVECFS
132. WORKCFS
133. IMFVPLA3
134. HPVADVC4
135. HPVADSHT
136. SHINGLE2
137. COVIDVA1
138. COVACGET
139. COVIDNU1
140. COVIDINT
141. COVIDFS1
142. COVIDSE1
143. COPDCOGH
144. COPDFLEM
145. COPDBRTH
146. COPDBTST
147. COPDSMOK
148. CNCRDIFF
149. CNCRAGE
150. CNCRTYP2
151. CSRVTRT3
152. CSRVDOC1
153. CSRVSUM
154. CSRVRTRN
155. CSRVINST
156. CSRVINSR
157. CSRVDEIN
158. CSRVCLIN
159. CSRVPAIN
160. CSRVCTL2
161. PSATEST1
162. PSATIME1
163. PCPSARS2
164. PSASUGST
165. PCSTALK1
166. CIMEMLOS
167. CDHOUSE
168. CDASSIST
169. CDHELP
170. CDSOCIAL
171. CDDISCUS
172. CAREGIV1
173. CRGVREL4
174. CRGVLNG1
175. CRGVHRS1
176. CRGVPRB3
177. CRGVALZD
178. CRGVPER1
179. CRGVHOU1
180. CRGVEXPT
181. ACEDEPRS
182. ACEDRINK
183. ACEDRUGS
184. ACEPRISN
185. ACEDIVRC
186. ACEPUNCH
187. ACEHURT1
188. ACESWEAR
189. ACETOUCH
190. ACETTHEM
191. ACEHVSEX
192. ACEADSAF
193. ACEADNED
194. LSATISFY
195. EMTSUPRT
196. SDHISOLT
197. SDHEMPLY
198. FOODSTMP
199. SDHFOOD1
200. SDHBILLS
201. SDHUTILS
202. SDHTRNSP
203. SDHSTRE1
204. MARIJAN1
205. MARJSMOK
206. MARJEAT
207. MARJVAPE
208. MARJDAB
209. MARJOTHR
210. USEMRJN4
211. LASTSMK2
212. STOPSMK2
213. MENTCIGS
214. MENTECIG
215. HEATTBCO
216. ASBIALCH
217. ASBIDRNK
218. ASBIBING
219. ASBIADVC
220. ASBIRDUC
221. FIREARM5
222. GUNLOAD
223. LOADULK2
224. RCSGEND1
225. RCSXBRTH
226. RCSRLTN2
227. CASTHDX2
228. CASTHNO2
229. BIRTHSEX
230. SOMALE
231. SOFEMALE
232. TRNSGNDR
233. HADSEX
234. PFPPRVN4
235. TYPCNTR9
236. BRTHCNT4
237. WHEREGET
238. NOBCUSE8
239. BCPREFER
240. RRCLASS3
241. RRCOGNT2
242. RRTREAT
243. RRATWRK2
244. RRHCARE4
245. RRPHYSM2
246. QSTVER
247. QSTLANG
248. _METSTAT
249. _URBSTAT
250. MSCODE
251. _STSTR
252. _STRWT
253. _RAWRAKE
254. _WT2RAKE
255. _IMPRACE
256. _CHISPNC
257. _CRACE2
258. _CPRACE2
259. CAGEG
260. _CLLCPWT
261. _DUALUSE
262. _DUALCOR
263. _LLCPWT2
264. _LLCPWT
265. _RFHLTH
266. _PHYS14D
267. _MENT14D
268. _HLTHPLN
269. _HCVU652
270. _TOTINDA
271. _EXTETH3
272. _ALTETH3
273. _DENVST3
274. _MICHD
275. _LTASTH1
276. _CASTHM1
277. _ASTHMS1
278. _DRDXAR2
279. _PRACE2
280. _MRACE2
281. _HISPANC
282. _RACE1
283. _RACEG22
284. _RACEGR4
285. _RACEPR1
286. _SEX
287. _AGEG5YR
288. _AGE65YR
289. _AGE80
290. _AGE_G
291. HTIN4
292. HTM4
293. WTKG3
294. _BMI5
295. _BMI5CAT
296. _RFBMI5
297. _CHLDCNT
298. _EDUCAG
299. _INCOMG1
300. _RFMAM22
301. _MAM5023
302. _HADCOLN
303. _CLNSCP1
304. _HADSIGM
305. _SGMSCP1
306. _SGMS101
307. _RFBLDS5
308. _STOLDN1
309. _VIRCOL1
310. _SBONTI1
311. _CRCREC2
312. _SMOKER3
313. _RFSMOK3
314. _CURECI2
315. _YRSSMOK
316. _PACKDAY
317. _PACKYRS
318. _YRSQUIT
319. _SMOKGRP
320. _LCSREC
321. DRNKANY6
322. DROCDY4_
323. _RFBING6
324. _DRNKWK2
325. _RFDRHV8
326. _FLSHOT7
327. _PNEUMO3
328. _AIDTST4

In [4]:
# Select the most relevant columns for heart disease prediction
columns_to_keep = [
    # TARGET VARIABLES (outcomes)
    'CVDINFR4',      # Heart attack
    'CVDCRHD4',      # Coronary heart disease
    'CVDSTRK3',      # Stroke
    '_MICHD',        # Computed heart disease indicator
    
    # DEMOGRAPHICS
    '_STATE',        # State
    '_SEX',          # Sex (computed)
    '_AGEG5YR',      # Age groups (5 year)
    '_AGE_G',        # Age groups
    '_IMPRACE',      # Imputed race/ethnicity
    '_EDUCAG',       # Education level
    '_INCOMG1',      # Income categories
    'MARITAL',       # Marital status
    'VETERAN3',      # Veteran status
    'EMPLOY1',       # Employment status
    
    # HEALTH STATUS
    'GENHLTH',       # General health
    'PHYSHLTH',      # Physical unhealthy days
    'MENTHLTH',      # Mental unhealthy days
    'POORHLTH',      # Poor health days
    '_RFHLTH',       # Computed health status
    '_PHYS14D',      # 14+ physically unhealthy days
    '_MENT14D',      # 14+ mentally unhealthy days
    
    # CHRONIC CONDITIONS (CRITICAL!)
    'DIABETE4',      # Diabetes status
    'HAVARTH4',      # Arthritis
    'CHCCOPD3',      # COPD
    'CHCKDNY2',      # Kidney disease
    'CHCSCNC1',      # Skin cancer
    'CHCOCNC1',      # Other cancer
    'ADDEPEV3',      # Depressive disorder
    'ASTHMA3',       # Ever had asthma
    
    # BMI & PHYSICAL MEASUREMENTS
    '_BMI5',         # Body Mass Index
    '_BMI5CAT',      # BMI categories
    '_RFBMI5',       # Overweight/obese indicator
    'HTIN4',         # Height in inches
    'WTKG3',         # Weight in kg
    
    # LIFESTYLE & BEHAVIORS
    'EXERANY2',      # Exercise in past 30 days
    '_TOTINDA',      # Physical activity (computed)
    'SLEPTIM1',      # Sleep hours
    'SMOKE100',      # Smoked 100+ cigarettes
    'SMOKDAY2',      # Current smoking frequency
    '_SMOKER3',      # Computed smoking status
    '_RFSMOK3',      # Current smoker
    'ALCDAY4',       # Days had alcohol
    '_RFBING6',      # Binge drinking
    '_DRNKWK2',      # Drinks per week
    '_RFDRHV8',      # Heavy drinking
    
    # HEALTHCARE ACCESS
    'PRIMINSR',      # Primary insurance
    '_HCVU652',      # Healthcare coverage
    'PERSDOC3',      # Has personal doctor
    'MEDCOST1',      # Could not afford care
    'CHECKUP1',      # Last checkup
    
    # DISABILITY/FUNCTIONING
    'DIFFWALK',      # Difficulty walking
    'DIFFDRES',      # Difficulty dressing
    'DIFFALON',      # Difficulty errands alone
    'DECIDE',        # Difficulty concentrating
    'DEAF',          # Deaf or hard of hearing
    'BLIND',         # Blind or vision difficulty
    
    # SOCIAL DETERMINANTS
    'SDHEMPLY',      # Worried about unemployment
    'SDHFOOD1',      # Food insecurity
    'SDHBILLS',      # Difficulty paying bills
    'SDHUTILS',      # Utilities shut off
    'SDHTRNSP',      # Lack of transportation
    'SDHSTRE1',      # Stress
    'LSATISFY',      # Life satisfaction
    'EMTSUPRT',      # Emotional support
    
    # PREVENTIVE CARE
    'FLUSHOT7',      # Flu shot
    'PNEUVAC4',      # Pneumonia vaccine
]

# Create filtered dataset
df_filtered = df[columns_to_keep].copy()

print(f"Original dataset: {df.shape}")
print(f"Filtered dataset: {df_filtered.shape}")
print(f"\nColumns kept: {len(columns_to_keep)}")

# Save filtered dataset
df_filtered.to_csv('LLCP2022_heart_disease.csv', index=False)
print("\n✓ Saved as 'LLCP2022_heart_disease.csv'")

# Check target variable distribution
print("\n=== TARGET VARIABLE DISTRIBUTION ===")
print("\nHeart Attack (CVDINFR4):")
print(df_filtered['CVDINFR4'].value_counts(dropna=False))
print("\nCoronary Heart Disease (CVDCRHD4):")
print(df_filtered['CVDCRHD4'].value_counts(dropna=False))
print("\nStroke (CVDSTRK3):")
print(df_filtered['CVDSTRK3'].value_counts(dropna=False))

Original dataset: (188473, 328)
Filtered dataset: (188473, 66)

Columns kept: 66

✓ Saved as 'LLCP2022_heart_disease.csv'

=== TARGET VARIABLE DISTRIBUTION ===

Heart Attack (CVDINFR4):
CVDINFR4
2.0    176400
1.0     10664
7.0      1237
9.0       170
NaN         2
Name: count, dtype: int64

Coronary Heart Disease (CVDCRHD4):
CVDCRHD4
2.0    175143
1.0     11381
7.0      1758
9.0       189
NaN         2
Name: count, dtype: int64

Stroke (CVDSTRK3):
CVDSTRK3
2.0    179305
1.0      8453
7.0       560
9.0       153
NaN         2
Name: count, dtype: int64

In [5]:
# Dictionary mapping old column names to meaningful new names
column_rename_dict = {
    # TARGET VARIABLES
    'CVDINFR4': 'heart_attack',
    'CVDCRHD4': 'coronary_heart_disease',
    'CVDSTRK3': 'stroke',
    '_MICHD': 'heart_disease_computed',
    
    # DEMOGRAPHICS
    '_STATE': 'state',
    '_SEX': 'sex',
    '_AGEG5YR': 'age_group_5yr',
    '_AGE_G': 'age_group',
    '_IMPRACE': 'race_ethnicity',
    '_EDUCAG': 'education_level',
    '_INCOMG1': 'income_category',
    'MARITAL': 'marital_status',
    'VETERAN3': 'veteran_status',
    'EMPLOY1': 'employment_status',
    
    # HEALTH STATUS
    'GENHLTH': 'general_health',
    'PHYSHLTH': 'physical_unhealthy_days',
    'MENTHLTH': 'mental_unhealthy_days',
    'POORHLTH': 'poor_health_days',
    '_RFHLTH': 'health_status_computed',
    '_PHYS14D': 'physical_unhealthy_14plus_days',
    '_MENT14D': 'mental_unhealthy_14plus_days',
    
    # CHRONIC CONDITIONS
    'DIABETE4': 'diabetes_status',
    'HAVARTH4': 'has_arthritis',
    'CHCCOPD3': 'has_copd',
    'CHCKDNY2': 'has_kidney_disease',
    'CHCSCNC1': 'has_skin_cancer',
    'CHCOCNC1': 'has_other_cancer',
    'ADDEPEV3': 'has_depression',
    'ASTHMA3': 'ever_had_asthma',
    
    # BMI & PHYSICAL MEASUREMENTS
    '_BMI5': 'bmi',
    '_BMI5CAT': 'bmi_category',
    '_RFBMI5': 'overweight_obese',
    'HTIN4': 'height_inches',
    'WTKG3': 'weight_kg',
    
    # LIFESTYLE & BEHAVIORS
    'EXERANY2': 'exercise_past_30days',
    '_TOTINDA': 'physical_activity',
    'SLEPTIM1': 'sleep_hours',
    'SMOKE100': 'smoked_100_cigarettes',
    'SMOKDAY2': 'current_smoking_frequency',
    '_SMOKER3': 'smoking_status',
    '_RFSMOK3': 'current_smoker',
    'ALCDAY4': 'alcohol_days',
    '_RFBING6': 'binge_drinking',
    '_DRNKWK2': 'drinks_per_week',
    '_RFDRHV8': 'heavy_drinking',
    
    # HEALTHCARE ACCESS
    'PRIMINSR': 'primary_insurance',
    '_HCVU652': 'has_healthcare_coverage',
    'PERSDOC3': 'has_personal_doctor',
    'MEDCOST1': 'could_not_afford_care',
    'CHECKUP1': 'last_checkup',
    
    # DISABILITY/FUNCTIONING
    'DIFFWALK': 'difficulty_walking',
    'DIFFDRES': 'difficulty_dressing',
    'DIFFALON': 'difficulty_errands',
    'DECIDE': 'difficulty_concentrating',
    'DEAF': 'hearing_difficulty',
    'BLIND': 'vision_difficulty',
    
    # SOCIAL DETERMINANTS
    'SDHEMPLY': 'worried_unemployment',
    'SDHFOOD1': 'food_insecurity',
    'SDHBILLS': 'difficulty_paying_bills',
    'SDHUTILS': 'utilities_shut_off',
    'SDHTRNSP': 'lack_transportation',
    'SDHSTRE1': 'stress_level',
    'LSATISFY': 'life_satisfaction',
    'EMTSUPRT': 'emotional_support',
    
    # PREVENTIVE CARE
    'FLUSHOT7': 'flu_shot',
    'PNEUVAC4': 'pneumonia_vaccine',
}

# Rename the columns
df_filtered = df_filtered.rename(columns=column_rename_dict)

print(f"✓ Columns renamed!")
print(f"\nNew column names:")
for i, col in enumerate(df_filtered.columns, 1):
    print(f"{i:2d}. {col}")

# Save the renamed dataset
df_filtered.to_csv('LLCP2022_heart_disease_clean.csv', index=False)
print(f"\n✓ Saved as 'LLCP2022_heart_disease_clean.csv'")

# Show a preview
print("\nPreview of data:")
df_filtered.head()

✓ Columns renamed!

New column names:
 1. heart_attack
 2. coronary_heart_disease
 3. stroke
 4. heart_disease_computed
 5. state
 6. sex
 7. age_group_5yr
 8. age_group
 9. race_ethnicity
10. education_level
11. income_category
12. marital_status
13. veteran_status
14. employment_status
15. general_health
16. physical_unhealthy_days
17. mental_unhealthy_days
18. poor_health_days
19. health_status_computed
20. physical_unhealthy_14plus_days
21. mental_unhealthy_14plus_days
22. diabetes_status
23. has_arthritis
24. has_copd
25. has_kidney_disease
26. has_skin_cancer
27. has_other_cancer
28. has_depression
29. ever_had_asthma
30. bmi
31. bmi_category
32. overweight_obese
33. height_inches
34. weight_kg
35. exercise_past_30days
36. physical_activity
37. sleep_hours
38. smoked_100_cigarettes
39. current_smoking_frequency
40. smoking_status
41. current_smoker
42. alcohol_days
43. binge_drinking
44. drinks_per_week
45. heavy_drinking
46. primary_insurance
47. has_healthcare_coverage
48. has_personal_doctor
49. could_not_afford_care
50. last_checkup
51. difficulty_walking
52. difficulty_dressing
53. difficulty_errands
54. difficulty_concentrating
55. hearing_difficulty
56. vision_difficulty
57. worried_unemployment
58. food_insecurity
59. difficulty_paying_bills
60. utilities_shut_off
61. lack_transportation
62. stress_level
63. life_satisfaction
64. emotional_support
65. flu_shot
66. pneumonia_vaccine

✓ Saved as 'LLCP2022_heart_disease_clean.csv'

Preview of data:

,heart_attack,coronary_heart_disease,stroke,heart_disease_computed,state,sex,age_group_5yr,age_group,race_ethnicity,education_level,...,worried_unemployment,food_insecurity,difficulty_paying_bills,utilities_shut_off,lack_transportation,stress_level,life_satisfaction,emotional_support,flu_shot,pneumonia_vaccine
0,2.0,2.0,2.0,2.0,1.0,2.0,13.0,6.0,1.0,4.0,...,2.0,5.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,2.0
1,2.0,2.0,2.0,2.0,1.0,2.0,13.0,6.0,1.0,2.0,...,2.0,5.0,2.0,2.0,2.0,5.0,1.0,1.0,2.0,2.0
2,2.0,2.0,2.0,2.0,1.0,2.0,8.0,5.0,1.0,4.0,...,2.0,5.0,2.0,2.0,2.0,5.0,2.0,2.0,2.0,2.0
3,2.0,2.0,2.0,2.0,1.0,2.0,14.0,6.0,1.0,2.0,...,2.0,5.0,2.0,2.0,2.0,5.0,1.0,1.0,1.0,1.0
4,2.0,2.0,2.0,2.0,1.0,2.0,5.0,3.0,1.0,3.0,...,2.0,5.0,2.0,2.0,2.0,5.0,1.0,1.0,2.0,1.0

In [9]:
# Quick look at the data
df_filtered.head()
df_filtered.info()
df_filtered.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188473 entries, 0 to 188472
Data columns (total 66 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   heart_attack                    188471 non-null  float64
 1   coronary_heart_disease          188471 non-null  float64
 2   stroke                          188471 non-null  float64
 3   heart_disease_computed          186221 non-null  float64
 4   state                           188473 non-null  float64
 5   sex                             188473 non-null  float64
 6   age_group_5yr                   188473 non-null  float64
 7   age_group                       188473 non-null  float64
 8   race_ethnicity                  188473 non-null  float64
 9   education_level                 188473 non-null  float64
 10  income_category                 188473 non-null  float64
 11  marital_status                  188471 non-null  float64
 12  veteran_status                  186670 non-null  float64
 13  employment_status               185770 non-null  float64
 14  general_health                  188471 non-null  float64
 15  physical_unhealthy_days         188468 non-null  float64
 16  mental_unhealthy_days           188471 non-null  float64
 17  poor_health_days                108144 non-null  float64
 18  health_status_computed          188473 non-null  float64
 19  physical_unhealthy_14plus_days  188473 non-null  float64
 20  mental_unhealthy_14plus_days    188473 non-null  float64
 21  diabetes_status                 188471 non-null  float64
 22  has_arthritis                   188471 non-null  float64
 23  has_copd                        188471 non-null  float64
 24  has_kidney_disease              188471 non-null  float64
 25  has_skin_cancer                 188471 non-null  float64
 26  has_other_cancer                188471 non-null  float64
 27  has_depression                  188467 non-null  float64
 28  ever_had_asthma                 188471 non-null  float64
 29  bmi                             167384 non-null  float64
 30  bmi_category                    167384 non-null  float64
 31  overweight_obese                188473 non-null  float64
 32  height_inches                   174020 non-null  float64
 33  weight_kg                       170335 non-null  float64
 34  exercise_past_30days            188471 non-null  float64
 35  physical_activity               188473 non-null  float64
 36  sleep_hours                     188471 non-null  float64
 37  smoked_100_cigarettes           174720 non-null  float64
 38  current_smoking_frequency       69772 non-null   float64
 39  smoking_status                  188473 non-null  float64
 40  current_smoker                  188473 non-null  float64
 41  alcohol_days                    170664 non-null  float64
 42  binge_drinking                  188473 non-null  float64
 43  drinks_per_week                 188473 non-null  float64
 44  heavy_drinking                  188473 non-null  float64
 45  primary_insurance               188469 non-null  float64
 46  has_healthcare_coverage         188473 non-null  float64
 47  has_personal_doctor             188471 non-null  float64
 48  could_not_afford_care           188469 non-null  float64
 49  last_checkup                    188470 non-null  float64
 50  difficulty_walking              178873 non-null  float64
 51  difficulty_dressing             178569 non-null  float64
 52  difficulty_errands              178123 non-null  float64
 53  difficulty_concentrating        179379 non-null  float64
 54  hearing_difficulty              180380 non-null  float64
 55  vision_difficulty               179871 non-null  float64
 56  worried_unemployment            109716 non-null  float64
 57  food_insecurity                 109412 non-null  float64
 58  difficulty_paying_bills         109292 non-null  float64
 59  utilities_shut_off              109177 non-null  float64
 60  lack_transportation             109028 non-null  float64
 61  stress_level                    108719 non-null  float64
 62  life_satisfaction               110101 non-null  float64
 63  emotional_support               109968 non-null  float64
 64  flu_shot                        169483 non-null  float64
 65  pneumonia_vaccine               169000 non-null  float64
dtypes: float64(66)
memory usage: 94.9 MB

,heart_attack,coronary_heart_disease,stroke,heart_disease_computed,state,sex,age_group_5yr,age_group,race_ethnicity,education_level,...,worried_unemployment,food_insecurity,difficulty_paying_bills,utilities_shut_off,lack_transportation,stress_level,life_satisfaction,emotional_support,flu_shot,pneumonia_vaccine
count,188471.000000,188471.000000,188471.000000,186221.000000,188473.000000,188473.000000,188473.000000,188473.000000,188473.000000,188473.000000,...,109716.000000,109412.000000,109292.000000,109177.000000,109028.000000,108719.000000,110101.000000,109968.000000,169483.000000,169000.000000
mean,1.982549,1.993272,1.975689,1.908850,14.965889,1.532055,7.795461,4.394401,1.725637,3.095993,...,1.966869,4.668263,1.957554,1.978869,1.967531,3.916785,1.693754,1.955251,1.526336,2.020385
std,0.514354,0.585382,0.397895,0.287823,7.451987,0.498973,3.683026,1.614874,1.433762,1.046961,...,0.673321,0.906549,0.623258,0.553838,0.532067,1.203476,0.949439,1.289742,0.780689,1.560919
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,2.000000,9.000000,1.000000,5.000000,3.000000,1.000000,2.000000,...,2.000000,5.000000,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000
50%,2.000000,2.000000,2.000000,2.000000,16.000000,2.000000,8.000000,5.000000,1.000000,3.000000,...,2.000000,5.000000,2.000000,2.000000,2.000000,4.000000,2.000000,2.000000,1.000000,2.000000
75%,2.000000,2.000000,2.000000,2.000000,22.000000,2.000000,11.000000,6.000000,2.000000,4.000000,...,2.000000,5.000000,2.000000,2.000000,2.000000,5.000000,2.000000,2.000000,2.000000,2.000000
max,9.000000,9.000000,9.000000,2.000000,26.000000,2.000000,14.000000,6.000000,6.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

In [8]:
df_filtered.head()

,heart_attack,coronary_heart_disease,stroke,heart_disease_computed,state,sex,age_group_5yr,age_group,race_ethnicity,education_level,...,worried_unemployment,food_insecurity,difficulty_paying_bills,utilities_shut_off,lack_transportation,stress_level,life_satisfaction,emotional_support,flu_shot,pneumonia_vaccine
0,2.0,2.0,2.0,2.0,1.0,2.0,13.0,6.0,1.0,4.0,...,2.0,5.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,2.0
1,2.0,2.0,2.0,2.0,1.0,2.0,13.0,6.0,1.0,2.0,...,2.0,5.0,2.0,2.0,2.0,5.0,1.0,1.0,2.0,2.0
2,2.0,2.0,2.0,2.0,1.0,2.0,8.0,5.0,1.0,4.0,...,2.0,5.0,2.0,2.0,2.0,5.0,2.0,2.0,2.0,2.0
3,2.0,2.0,2.0,2.0,1.0,2.0,14.0,6.0,1.0,2.0,...,2.0,5.0,2.0,2.0,2.0,5.0,1.0,1.0,1.0,1.0
4,2.0,2.0,2.0,2.0,1.0,2.0,5.0,3.0,1.0,3.0,...,2.0,5.0,2.0,2.0,2.0,5.0,1.0,1.0,2.0,1.0

In [10]:
import pandas as pd
import numpy as np

# First, let's examine what actual values we have in each column
print("=" * 80)
print("EXAMINING ACTUAL VALUES IN YOUR DATA")
print("=" * 80)

# Check a few key columns to see what values they contain
sample_cols = ['heart_attack', 'coronary_heart_disease', 'stroke', 'sex', 
               'general_health', 'diabetes_status', 'bmi_category']

for col in sample_cols:
    if col in df_filtered.columns:
        print(f"\n{col}:")
        print(f"  Data type: {df_filtered[col].dtype}")
        print(f"  Unique values: {sorted(df_filtered[col].dropna().unique())}")
        print(f"  Value counts:")
        print(df_filtered[col].value_counts(dropna=False).head(10))
        print("-" * 60)

# Check ALL columns and their unique values
print("\n" + "=" * 80)
print("ALL COLUMNS - UNIQUE VALUES")
print("=" * 80)

for col in df_filtered.columns:
    unique_vals = sorted(df_filtered[col].dropna().unique())
    n_unique = len(unique_vals)
    
    # Show first 15 unique values
    if n_unique <= 15:
        print(f"\n{col}:")
        print(f"  Unique count: {n_unique}")
        print(f"  Values: {unique_vals}")
    else:
        print(f"\n{col}:")
        print(f"  Unique count: {n_unique}")
        print(f"  Sample values: {unique_vals[:15]}...")

================================================================================
EXAMINING ACTUAL VALUES IN YOUR DATA
================================================================================

heart_attack:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]
  Value counts:
heart_attack
2.0    176400
1.0     10664
7.0      1237
9.0       170
NaN         2
Name: count, dtype: int64
------------------------------------------------------------

coronary_heart_disease:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]
  Value counts:
coronary_heart_disease
2.0    175143
1.0     11381
7.0      1758
9.0       189
NaN         2
Name: count, dtype: int64
------------------------------------------------------------

stroke:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]
  Value counts:
stroke
2.0    179305
1.0      8453
7.0       560
9.0       153
NaN         2
Name: count, dtype: int64
------------------------------------------------------------

sex:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0)]
  Value counts:
sex
2.0    100278
1.0     88195
Name: count, dtype: int64
------------------------------------------------------------

general_health:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(7.0), np.float64(9.0)]
  Value counts:
general_health
2.0    62731
3.0    60933
1.0    30660
4.0    25267
5.0     8357
7.0      324
9.0      199
NaN        2
Name: count, dtype: int64
------------------------------------------------------------

diabetes_status:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(7.0), np.float64(9.0)]
  Value counts:
diabetes_status
3.0    155825
1.0     26142
4.0      4256
2.0      1732
7.0       331
9.0       185
NaN         2
Name: count, dtype: int64
------------------------------------------------------------

bmi_category:
  Data type: float64
  Unique values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0)]
  Value counts:
bmi_category
3.0    58774
4.0    54999
2.0    50609
NaN    21089
1.0     3002
Name: count, dtype: int64
------------------------------------------------------------

================================================================================
ALL COLUMNS - UNIQUE VALUES
================================================================================

heart_attack:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

coronary_heart_disease:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

stroke:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

heart_disease_computed:
  Unique count: 2
  Values: [np.float64(1.0), np.float64(2.0)]

state:
  Unique count: 23
  Sample values: [np.float64(1.0), np.float64(2.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(15.0), np.float64(16.0), np.float64(17.0), np.float64(18.0)]...

sex:
  Unique count: 2
  Values: [np.float64(1.0), np.float64(2.0)]

age_group_5yr:
  Unique count: 14
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0)]

age_group:
  Unique count: 6
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0)]

race_ethnicity:
  Unique count: 6
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0)]

education_level:
  Unique count: 5
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(9.0)]

income_category:
  Unique count: 8
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(9.0)]

marital_status:
  Unique count: 7
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(9.0)]

veteran_status:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

employment_status:
  Unique count: 9
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]

general_health:
  Unique count: 7
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(7.0), np.float64(9.0)]

physical_unhealthy_days:
  Unique count: 33
  Sample values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0)]...

mental_unhealthy_days:
  Unique count: 33
  Sample values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0)]...

poor_health_days:
  Unique count: 33
  Sample values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0)]...

health_status_computed:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

physical_unhealthy_14plus_days:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(9.0)]

mental_unhealthy_14plus_days:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(9.0)]

diabetes_status:
  Unique count: 6
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(7.0), np.float64(9.0)]

has_arthritis:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

has_copd:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

has_kidney_disease:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

has_skin_cancer:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

has_other_cancer:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

has_depression:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

ever_had_asthma:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

bmi:
  Unique count: 3363
  Sample values: [np.float64(1215.0), np.float64(1216.0), np.float64(1219.0), np.float64(1220.0), np.float64(1221.0), np.float64(1224.0), np.float64(1227.0), np.float64(1230.0), np.float64(1240.0), np.float64(1244.0), np.float64(1248.0), np.float64(1250.0), np.float64(1255.0), np.float64(1269.0), np.float64(1275.0)]...

bmi_category:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0)]

overweight_obese:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

height_inches:
  Unique count: 55
  Sample values: [np.float64(36.0), np.float64(38.0), np.float64(39.0), np.float64(41.0), np.float64(42.0), np.float64(43.0), np.float64(44.0), np.float64(45.0), np.float64(47.0), np.float64(48.0), np.float64(49.0), np.float64(50.0), np.float64(51.0), np.float64(52.0), np.float64(53.0)]...

weight_kg:
  Unique count: 522
  Sample values: [np.float64(2268.0), np.float64(2359.0), np.float64(2400.0), np.float64(2404.0), np.float64(2449.0), np.float64(2495.0), np.float64(2540.0), np.float64(2585.0), np.float64(2600.0), np.float64(2631.0), np.float64(2722.0), np.float64(2858.0), np.float64(2903.0), np.float64(2948.0), np.float64(3000.0)]...

exercise_past_30days:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

physical_activity:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

sleep_hours:
  Unique count: 26
  Sample values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0)]...

smoked_100_cigarettes:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

current_smoking_frequency:
  Unique count: 5
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(7.0), np.float64(9.0)]

smoking_status:
  Unique count: 5
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(9.0)]

current_smoker:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

alcohol_days:
  Unique count: 43
  Sample values: [np.float64(101.0), np.float64(102.0), np.float64(103.0), np.float64(104.0), np.float64(105.0), np.float64(106.0), np.float64(107.0), np.float64(115.0), np.float64(130.0), np.float64(150.0), np.float64(201.0), np.float64(202.0), np.float64(203.0), np.float64(204.0), np.float64(205.0)]...

binge_drinking:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

drinks_per_week:
  Unique count: 226
  Sample values: [np.float64(5.397605346934028e-79), np.float64(23.0), np.float64(47.0), np.float64(70.0), np.float64(93.0), np.float64(100.0), np.float64(117.0), np.float64(140.0), np.float64(163.0), np.float64(187.0), np.float64(200.0), np.float64(210.0), np.float64(233.0), np.float64(257.0), np.float64(280.0)]...

heavy_drinking:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

primary_insurance:
  Unique count: 13
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(77.0), np.float64(88.0), np.float64(99.0)]

has_healthcare_coverage:
  Unique count: 3
  Values: [np.float64(1.0), np.float64(2.0), np.float64(9.0)]

has_personal_doctor:
  Unique count: 5
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(7.0), np.float64(9.0)]

could_not_afford_care:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

last_checkup:
  Unique count: 7
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(7.0), np.float64(8.0), np.float64(9.0)]

difficulty_walking:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

difficulty_dressing:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

difficulty_errands:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

difficulty_concentrating:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

hearing_difficulty:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

vision_difficulty:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

worried_unemployment:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

food_insecurity:
  Unique count: 7
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(7.0), np.float64(9.0)]

difficulty_paying_bills:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

utilities_shut_off:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

lack_transportation:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

stress_level:
  Unique count: 7
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(7.0), np.float64(9.0)]

life_satisfaction:
  Unique count: 6
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(7.0), np.float64(9.0)]

emotional_support:
  Unique count: 7
  Values: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(7.0), np.float64(9.0)]

flu_shot:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

pneumonia_vaccine:
  Unique count: 4
  Values: [np.float64(1.0), np.float64(2.0), np.float64(7.0), np.float64(9.0)]

In [11]:
import pandas as pd
import numpy as np

# Create a copy to work with
df_decoded = df_filtered.copy()

print("Starting data decoding...")

# ============================================================================
# DECODE ALL COLUMNS TO MEANINGFUL TEXT
# ============================================================================

# TARGET VARIABLES - Heart Disease (1=Yes, 2=No, 7=Don't know, 9=Refused)
yes_no_dict = {1.0: 'Yes', 2.0: 'No', 7.0: 'Unknown', 9.0: 'Refused'}

df_decoded['heart_attack'] = df_decoded['heart_attack'].map(yes_no_dict)
df_decoded['coronary_heart_disease'] = df_decoded['coronary_heart_disease'].map(yes_no_dict)
df_decoded['stroke'] = df_decoded['stroke'].map(yes_no_dict)

# Heart Disease Computed (1=No, 2=Yes)
df_decoded['heart_disease_computed'] = df_decoded['heart_disease_computed'].map({
    1.0: 'No', 2.0: 'Yes'
})

# SEX (1=Male, 2=Female)
df_decoded['sex'] = df_decoded['sex'].map({
    1.0: 'Male', 2.0: 'Female'
})

# AGE GROUPS
df_decoded['age_group_5yr'] = df_decoded['age_group_5yr'].map({
    1.0: '18-24', 2.0: '25-29', 3.0: '30-34', 4.0: '35-39',
    5.0: '40-44', 6.0: '45-49', 7.0: '50-54', 8.0: '55-59',
    9.0: '60-64', 10.0: '65-69', 11.0: '70-74', 12.0: '75-79',
    13.0: '80+', 14.0: 'Unknown'
})

df_decoded['age_group'] = df_decoded['age_group'].map({
    1.0: '18-24', 2.0: '25-34', 3.0: '35-44',
    4.0: '45-54', 5.0: '55-64', 6.0: '65+'
})

# RACE/ETHNICITY
df_decoded['race_ethnicity'] = df_decoded['race_ethnicity'].map({
    1.0: 'White', 2.0: 'Black', 3.0: 'Asian',
    4.0: 'Native American/Alaska Native', 5.0: 'Hispanic', 6.0: 'Other'
})

# EDUCATION LEVEL
df_decoded['education_level'] = df_decoded['education_level'].map({
    1.0: 'Did not graduate High School',
    2.0: 'High School Graduate',
    3.0: 'Some College',
    4.0: 'College Graduate',
    9.0: 'Unknown'
})

# INCOME CATEGORY (appears to have more categories than expected)
df_decoded['income_category'] = df_decoded['income_category'].map({
    1.0: 'Less than $15,000',
    2.0: '$15,000 to <$25,000',
    3.0: '$25,000 to <$35,000',
    4.0: '$35,000 to <$50,000',
    5.0: '$50,000 to <$100,000',
    6.0: '$100,000 to <$200,000',
    7.0: '$200,000+',
    9.0: 'Unknown'
})

# MARITAL STATUS
df_decoded['marital_status'] = df_decoded['marital_status'].map({
    1.0: 'Married',
    2.0: 'Divorced',
    3.0: 'Widowed',
    4.0: 'Separated',
    5.0: 'Never Married',
    6.0: 'Unmarried Couple',
    9.0: 'Refused'
})

# VETERAN STATUS
df_decoded['veteran_status'] = df_decoded['veteran_status'].map(yes_no_dict)

# EMPLOYMENT STATUS
df_decoded['employment_status'] = df_decoded['employment_status'].map({
    1.0: 'Employed for wages',
    2.0: 'Self-employed',
    3.0: 'Out of work <1 year',
    4.0: 'Out of work 1+ years',
    5.0: 'Homemaker',
    6.0: 'Student',
    7.0: 'Retired',
    8.0: 'Unable to work',
    9.0: 'Refused'
})

# GENERAL HEALTH
df_decoded['general_health'] = df_decoded['general_health'].map({
    1.0: 'Excellent',
    2.0: 'Very Good',
    3.0: 'Good',
    4.0: 'Fair',
    5.0: 'Poor',
    7.0: 'Unknown',
    9.0: 'Refused'
})

# HEALTH STATUS COMPUTED
df_decoded['health_status_computed'] = df_decoded['health_status_computed'].map({
    1.0: 'Good or Better', 2.0: 'Fair or Poor', 9.0: 'Unknown'
})

# 14+ UNHEALTHY DAYS
unhealthy_14_dict = {1.0: 'No', 2.0: 'Yes', 3.0: 'None', 9.0: 'Unknown'}
df_decoded['physical_unhealthy_14plus_days'] = df_decoded['physical_unhealthy_14plus_days'].map(unhealthy_14_dict)
df_decoded['mental_unhealthy_14plus_days'] = df_decoded['mental_unhealthy_14plus_days'].map(unhealthy_14_dict)

# DIABETES STATUS
df_decoded['diabetes_status'] = df_decoded['diabetes_status'].map({
    1.0: 'Yes',
    2.0: 'Yes, during pregnancy only',
    3.0: 'No',
    4.0: 'Pre-diabetes/Borderline',
    7.0: 'Unknown',
    9.0: 'Refused'
})

# CHRONIC CONDITIONS (Yes/No)
chronic_conditions = ['has_arthritis', 'has_copd', 'has_kidney_disease',
                     'has_skin_cancer', 'has_other_cancer', 'has_depression',
                     'ever_had_asthma']
for col in chronic_conditions:
    df_decoded[col] = df_decoded[col].map(yes_no_dict)

# BMI CATEGORY
df_decoded['bmi_category'] = df_decoded['bmi_category'].map({
    1.0: 'Underweight',
    2.0: 'Normal Weight',
    3.0: 'Overweight',
    4.0: 'Obese'
})

# OVERWEIGHT/OBESE
df_decoded['overweight_obese'] = df_decoded['overweight_obese'].map({
    1.0: 'No', 2.0: 'Yes', 9.0: 'Unknown'
})

# BMI - divide by 100 to get actual BMI
df_decoded['bmi'] = df_decoded['bmi'] / 100

# WEIGHT - divide by 100 to get actual kg
df_decoded['weight_kg'] = df_decoded['weight_kg'] / 100

# LIFESTYLE BEHAVIORS
df_decoded['exercise_past_30days'] = df_decoded['exercise_past_30days'].map(yes_no_dict)
df_decoded['physical_activity'] = df_decoded['physical_activity'].map({
    1.0: 'Yes', 2.0: 'No', 9.0: 'Unknown'
})

df_decoded['smoked_100_cigarettes'] = df_decoded['smoked_100_cigarettes'].map(yes_no_dict)

df_decoded['current_smoking_frequency'] = df_decoded['current_smoking_frequency'].map({
    1.0: 'Every day',
    2.0: 'Some days',
    3.0: 'Not at all',
    7.0: 'Unknown',
    9.0: 'Refused'
})

df_decoded['smoking_status'] = df_decoded['smoking_status'].map({
    1.0: 'Current smoker - every day',
    2.0: 'Current smoker - some days',
    3.0: 'Former smoker',
    4.0: 'Never smoked',
    9.0: 'Unknown'
})

df_decoded['current_smoker'] = df_decoded['current_smoker'].map({
    1.0: 'No', 2.0: 'Yes', 9.0: 'Unknown'
})

# ALCOHOL
df_decoded['binge_drinking'] = df_decoded['binge_drinking'].map({
    1.0: 'No', 2.0: 'Yes', 9.0: 'Unknown'
})

df_decoded['heavy_drinking'] = df_decoded['heavy_drinking'].map({
    1.0: 'No', 2.0: 'Yes', 9.0: 'Unknown'
})

# Drinks per week - divide by 100 to get actual number
df_decoded['drinks_per_week'] = df_decoded['drinks_per_week'] / 100

# HEALTHCARE ACCESS
df_decoded['primary_insurance'] = df_decoded['primary_insurance'].map({
    1.0: 'Employer',
    2.0: 'Purchased directly',
    3.0: 'Medicare',
    4.0: 'Medigap',
    5.0: 'Medicaid',
    6.0: 'CHAMPUS/TRICARE/VA',
    7.0: 'Indian Health Service',
    8.0: 'State program',
    9.0: 'Other',
    10.0: 'No coverage',
    77.0: 'Unknown',
    88.0: 'No coverage',
    99.0: 'Refused'
})

df_decoded['has_healthcare_coverage'] = df_decoded['has_healthcare_coverage'].map({
    1.0: 'Yes', 2.0: 'No', 9.0: 'Unknown'
})

df_decoded['has_personal_doctor'] = df_decoded['has_personal_doctor'].map({
    1.0: 'Yes, only one',
    2.0: 'More than one',
    3.0: 'No',
    7.0: 'Unknown',
    9.0: 'Refused'
})

df_decoded['could_not_afford_care'] = df_decoded['could_not_afford_care'].map(yes_no_dict)

df_decoded['last_checkup'] = df_decoded['last_checkup'].map({
    1.0: 'Within past year',
    2.0: '1-2 years ago',
    3.0: '2-5 years ago',
    4.0: '5+ years ago',
    7.0: 'Unknown',
    8.0: 'Never',
    9.0: 'Refused'
})

# DISABILITY/FUNCTIONING
disability_cols = ['difficulty_walking', 'difficulty_dressing', 'difficulty_errands',
                  'difficulty_concentrating', 'hearing_difficulty', 'vision_difficulty']
for col in disability_cols:
    df_decoded[col] = df_decoded[col].map(yes_no_dict)

# SOCIAL DETERMINANTS
df_decoded['worried_unemployment'] = df_decoded['worried_unemployment'].map(yes_no_dict)

df_decoded['food_insecurity'] = df_decoded['food_insecurity'].map({
    1.0: 'Always',
    2.0: 'Usually',
    3.0: 'Sometimes',
    4.0: 'Rarely',
    5.0: 'Never',
    7.0: 'Unknown',
    9.0: 'Refused'
})

df_decoded['difficulty_paying_bills'] = df_decoded['difficulty_paying_bills'].map(yes_no_dict)
df_decoded['utilities_shut_off'] = df_decoded['utilities_shut_off'].map(yes_no_dict)
df_decoded['lack_transportation'] = df_decoded['lack_transportation'].map(yes_no_dict)

df_decoded['stress_level'] = df_decoded['stress_level'].map({
    1.0: 'Not at all',
    2.0: 'A little bit',
    3.0: 'Moderately',
    4.0: 'Quite a bit',
    5.0: 'A great deal',
    7.0: 'Unknown',
    9.0: 'Refused'
})

df_decoded['life_satisfaction'] = df_decoded['life_satisfaction'].map({
    1.0: 'Very satisfied',
    2.0: 'Satisfied',
    3.0: 'Dissatisfied',
    4.0: 'Very dissatisfied',
    7.0: 'Unknown',
    9.0: 'Refused'
})

df_decoded['emotional_support'] = df_decoded['emotional_support'].map({
    1.0: 'Always',
    2.0: 'Usually',
    3.0: 'Sometimes',
    4.0: 'Rarely',
    5.0: 'Never',
    7.0: 'Unknown',
    9.0: 'Refused'
})

# PREVENTIVE CARE
df_decoded['flu_shot'] = df_decoded['flu_shot'].map(yes_no_dict)
df_decoded['pneumonia_vaccine'] = df_decoded['pneumonia_vaccine'].map(yes_no_dict)

print("✓ All columns decoded successfully!")

# Save the decoded dataset
df_decoded.to_csv('LLCP2022_heart_disease_decoded.csv', index=False)
print(f"✓ Saved as 'LLCP2022_heart_disease_decoded.csv'")
print(f"  Shape: {df_decoded.shape}")

# Display sample
print("\n" + "="*80)
print("SAMPLE OF DECODED DATA (First 10 rows, key columns)")
print("="*80)
sample_cols = ['age_group_5yr', 'sex', 'general_health', 'bmi_category',
               'heart_attack', 'coronary_heart_disease', 'stroke',
               'diabetes_status', 'smoking_status']
print(df_decoded[sample_cols].head(10))

Show target variable distribution
print("\n" + "="*80)
print("TARGET VARIABLE DISTRIBUTION")
print("="*80)

print("\n1. Heart Attack:")
print(df_decoded['heart_attack'].value_counts())
print(f"   Prevalence: {(df_decoded['heart_attack'] == 'Yes').sum() / len(df_decoded) * 100:.2f}%")

print("\n2. Coronary Heart Disease:")
print(df_decoded['coronary_heart# _disease'].value_counts())
print(f"   Prevalence: {(df_decoded['coronary_heart_disease'] == 'Yes').sum() / len(df_decoded) * 100:.2f}%")

print("\n3. Stroke:")
print(df_decoded['stroke'].value_counts())
print(f"   Prevalence: {(df_decoded['stroke'] == 'Yes').sum() / len(df_decoded) * 100:.2f}%")

print("\n" + "="*80)
print("✓ DATA READY FOR ANALYSIS!")
print("="*80)

Starting data decoding...
✓ All columns decoded successfully!
✓ Saved as 'LLCP2022_heart_disease_decoded.csv'
  Shape: (188473, 66)

================================================================================
SAMPLE OF DECODED DATA (First 10 rows, key columns)
================================================================================
  age_group_5yr     sex general_health   bmi_category heart_attack  \
0           80+  Female      Very Good            NaN           No
1           80+  Female      Excellent     Overweight           No
2         55-59  Female      Very Good     Overweight           No
3       Unknown  Female      Excellent  Normal Weight           No
4         40-44  Female           Fair  Normal Weight           No
5           80+    Male           Poor     Overweight          Yes
6           80+  Female      Very Good  Normal Weight           No
7           80+  Female           Good     Overweight           No
8         75-79  Female           Good            NaN           No
9         70-74  Female           Good     Overweight           No

  coronary_heart_disease stroke diabetes_status              smoking_status
0                     No     No             Yes                Never smoked
1                     No     No              No                Never smoked
2                     No     No              No                Never smoked
3                     No     No              No  Current smoker - some days
4                     No     No              No                Never smoked
5                     No    Yes             Yes                Never smoked
6                     No     No              No               Former smoker
7                     No     No              No                Never smoked
8                     No     No              No               Former smoker
9                     No     No             Yes                Never smoked

================================================================================
TARGET VARIABLE DISTRIBUTION
================================================================================

1. Heart Attack:
heart_attack
No         176400
Yes         10664
Unknown      1237
Refused       170
Name: count, dtype: int64
   Prevalence: 5.66%

2. Coronary Heart Disease:
coronary_heart_disease
No         175143
Yes         11381
Unknown      1758
Refused       189
Name: count, dtype: int64
   Prevalence: 6.04%

3. Stroke:
stroke
No         179305
Yes          8453
Unknown       560
Refused       153
Name: count, dtype: int64
   Prevalence: 4.48%

================================================================================
✓ DATA READY FOR ANALYSIS!
================================================================================

In [21]:
df_decoded.head(10)

,heart_attack,coronary_heart_disease,stroke,heart_disease_computed,state,sex,age_group_5yr,age_group,race_ethnicity,education_level,...,worried_unemployment,food_insecurity,difficulty_paying_bills,utilities_shut_off,lack_transportation,stress_level,life_satisfaction,emotional_support,flu_shot,pneumonia_vaccine
0,No,No,No,Yes,1.0,Female,80+,65+,White,College Graduate,...,No,Never,No,No,No,Quite a bit,Very satisfied,Always,Yes,No
1,No,No,No,Yes,1.0,Female,80+,65+,White,High School Graduate,...,No,Never,No,No,No,A great deal,Very satisfied,Always,No,No
2,No,No,No,Yes,1.0,Female,55-59,55-64,White,College Graduate,...,No,Never,No,No,No,A great deal,Satisfied,Usually,No,No
3,No,No,No,Yes,1.0,Female,Unknown,65+,White,High School Graduate,...,No,Never,No,No,No,A great deal,Very satisfied,Always,Yes,Yes
4,No,No,No,Yes,1.0,Female,40-44,35-44,White,Some College,...,No,Never,No,No,No,A great deal,Very satisfied,Always,No,Yes
5,Yes,No,Yes,No,1.0,Male,80+,65+,White,High School Graduate,...,No,Never,No,No,No,A great deal,Satisfied,Usually,No,Yes
6,No,No,No,Yes,1.0,Female,80+,65+,Black,College Graduate,...,No,Never,No,No,No,A great deal,Very satisfied,Always,No,No
7,No,No,No,Yes,1.0,Female,80+,65+,White,High School Graduate,...,No,Never,No,No,No,A great deal,Very satisfied,Always,Yes,Yes
8,No,No,No,Yes,1.0,Female,75-79,65+,White,College Graduate,...,Yes,Never,No,No,No,A great deal,Very satisfied,Always,No,No
9,No,No,No,Yes,1.0,Female,70-74,65+,White,College Graduate,...,No,Never,No,No,No,Quite a bit,Very satisfied,Always,Yes,Yes

In [14]:
import pandas as pd

# Update with your real CSV path
df = pd.read_csv("/Users/deirdreoconnor/Desktop/Ai Start Course 2/Course Materials/Week 5/Week 5 - Additional Files/Demos/Code/heart_2022_with_nans.csv")

# Show how many columns and what they are
print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist()[:50])  # show the first 50 columns

Shape: (445132, 40)
Columns:
['State', 'Sex', 'GeneralHealth', 'PhysicalHealthDays', 'MentalHealthDays', 'LastCheckupTime', 'PhysicalActivities', 'SleepHours', 'RemovedTeeth', 'HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis', 'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus', 'ECigaretteUsage', 'ChestScan', 'RaceEthnicityCategory', 'AgeCategory', 'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap', 'HighRiskLastYear', 'CovidPos']

In [15]:
df.head(10)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,NaN,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,NaN,No,...,1.60,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,NaN,No,...,1.57,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,NaN,No,...,1.57,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No
5,Alabama,Male,Poor,1.0,0.0,Within past year (anytime less than 12 months ...,No,7.0,NaN,Yes,...,1.80,84.82,26.08,No,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No
6,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,62.60,22.96,Yes,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
7,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,1.63,73.48,27.81,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
8,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,NaN,No,...,1.70,NaN,NaN,No,Yes,No,No,"Yes, received tetanus shot but not sure what type",No,No
9,Alabama,Female,Good,1.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.68,81.65,29.05,Yes,NaN,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [20]:
#Show target variable distribution
print("\n" + "="*80)
print("TARGET VARIABLE DISTRIBUTION")
print("="*80)

print("\n1. Heart Attack:")
print(df['HadHeartAttack'].value_counts())
print(f"   Prevalence: {(df['HadHeartAttack'] == 'Yes').sum() / len(df_decoded) * 100:.2f}%")

print("\n2. Had Angina:")
print(df['HadAngina'].value_counts())
print(f"   Prevalence: {(df['HadAngina'] == 'Yes').sum() / len(df) * 100:.2f}%")

print("\n3. Stroke:")
print(df['HadStroke'].value_counts())
print(f"   Prevalence: {(df['HadStroke'] == 'Yes').sum() / len(df) * 100:.2f}%")

print("\n" + "="*80)
print("✓ DATA READY FOR ANALYSIS!")
print("="*80)

================================================================================
TARGET VARIABLE DISTRIBUTION
================================================================================

1. Heart Attack:
HadHeartAttack
No     416959
Yes     25108
Name: count, dtype: int64
   Prevalence: 13.32%

2. Had Angina:
HadAngina
No     414176
Yes     26551
Name: count, dtype: int64
   Prevalence: 5.96%

3. Stroke:
HadStroke
No     424336
Yes     19239
Name: count, dtype: int64
   Prevalence: 4.32%

================================================================================
✓ DATA READY FOR ANALYSIS!
================================================================================

In [22]:
df_decoded.isnull().sum()

heart_attack                  2
coronary_heart_disease        2
stroke                        2
heart_disease_computed     2252
state                         0
                          ...
stress_level              79754
life_satisfaction         78372
emotional_support         78505
flu_shot                  18990
pneumonia_vaccine         19473
Length: 66, dtype: int64

In [23]:
df.isnull().sum()

State                            0
Sex                              0
GeneralHealth                 1198
PhysicalHealthDays           10927
MentalHealthDays              9067
LastCheckupTime               8308
PhysicalActivities            1093
SleepHours                    5453
RemovedTeeth                 11360
HadHeartAttack                3065
HadAngina                     4405
HadStroke                     1557
HadAsthma                     1773
HadSkinCancer                 3143
HadCOPD                       2219
HadDepressiveDisorder         2812
HadKidneyDisease              1926
HadArthritis                  2633
HadDiabetes                   1087
DeafOrHardOfHearing          20647
BlindOrVisionDifficulty      21564
DifficultyConcentrating      24240
DifficultyWalking            24012
DifficultyDressingBathing    23915
DifficultyErrands            25656
SmokerStatus                 35462
ECigaretteUsage              35660
ChestScan                    56046
RaceEthnicityCategory        14057
AgeCategory                   9079
HeightInMeters               28652
WeightInKilograms            42078
BMI                          48806
AlcoholDrinkers              46574
HIVTesting                   66127
FluVaxLast12                 47121
PneumoVaxEver                77040
TetanusLast10Tdap            82516
HighRiskLastYear             50623
CovidPos                     50764
dtype: int64

In [24]:
import pandas as pd

# Update with your real CSV path
df_cleaned = pd.read_csv("/Users/deirdreoconnor/Desktop/Ai Start Course 2/Course Materials/Week 5/Week 5 - Additional Files/Demos/Code/heart_2020_cleaned.csv")

# Show how many columns and what they are
print("Shape:", df_cleaned.shape)
print("Columns:")
print(df_cleaned.columns.tolist()[:50])  # show the first 50 columns

Shape: (319795, 18)
Columns:
['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke', 'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime', 'Asthma', 'KidneyDisease', 'SkinCancer']